-- Chạy file này trong Supabase > SQL Editor.
-- File này tạo/cập nhật database để app đồng bộ theo từng tài khoản đăng nhập.

create table if not exists schedule_rows (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text,
  start text,
  "end" text,
  tasks jsonb default '{}'::jsonb,
  week_key text,
  "spanText" text,
  "spanColor" text,
  created_at timestamptz default now()
);

-- Cập nhật cho database đã tạo trước đây: thêm week_key để mỗi tuần có lịch riêng.
alter table schedule_rows add column if not exists week_key text;

create table if not exists completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  completion_key text not null,
  week_key text not null,
  created_at timestamptz default now(),
  unique (user_id, completion_key, week_key)
);

create table if not exists chore_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  completion_key text not null,
  week_key text not null,
  created_at timestamptz default now(),
  unique (user_id, completion_key, week_key)
);

create table if not exists app_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  key text not null,
  value text,
  updated_at timestamptz default now(),
  unique (user_id, key)
);

alter table schedule_rows enable row level security;
alter table completions enable row level security;
alter table chore_completions enable row level security;
alter table app_settings enable row level security;

-- Xóa policy cũ nếu có
DO $$
DECLARE
  pol record;
BEGIN
  FOR pol IN
    SELECT schemaname, tablename, policyname
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename IN ('schedule_rows','completions','chore_completions','app_settings')
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I', pol.policyname, pol.schemaname, pol.tablename);
  END LOOP;
END $$;

-- schedule_rows
create policy "Users can view own schedule rows"
on schedule_rows for select
using ((select auth.uid()) = user_id);

create policy "Users can insert own schedule rows"
on schedule_rows for insert
with check ((select auth.uid()) = user_id);

create policy "Users can update own schedule rows"
on schedule_rows for update
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete own schedule rows"
on schedule_rows for delete
using ((select auth.uid()) = user_id);

-- completions
create policy "Users can view own completions"
on completions for select
using ((select auth.uid()) = user_id);

create policy "Users can insert own completions"
on completions for insert
with check ((select auth.uid()) = user_id);

create policy "Users can update own completions"
on completions for update
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete own completions"
on completions for delete
using ((select auth.uid()) = user_id);

-- chore_completions
create policy "Users can view own chore completions"
on chore_completions for select
using ((select auth.uid()) = user_id);

create policy "Users can insert own chore completions"
on chore_completions for insert
with check ((select auth.uid()) = user_id);

create policy "Users can update own chore completions"
on chore_completions for update
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete own chore completions"
on chore_completions for delete
using ((select auth.uid()) = user_id);

-- app_settings
create policy "Users can view own app settings"
on app_settings for select
using ((select auth.uid()) = user_id);

create policy "Users can insert own app settings"
on app_settings for insert
with check ((select auth.uid()) = user_id);

create policy "Users can update own app settings"
on app_settings for update
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete own app settings"
on app_settings for delete
using ((select auth.uid()) = user_id);

create index if not exists schedule_rows_user_id_idx on schedule_rows(user_id);
create index if not exists schedule_rows_user_week_idx on schedule_rows(user_id, week_key);
create index if not exists completions_user_week_idx on completions(user_id, week_key);
create index if not exists chore_completions_user_week_idx on chore_completions(user_id, week_key);
create index if not exists app_settings_user_key_idx on app_settings(user_id, key);
